config/routes.rb
require 'housing_first/api/base'

Rails.application.routes.draw do

  get '/helps/matching_service_providers' => 'helps#matching_service_providers'
  resources :helps
  resources :intake_forms
  devise_for :users
  get 'pages/index'
  root 'pages#index'

  get '/give' => 'pages#give'
  get '/search' => 'pages#find_client_profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :organizations, only: [:index, :show]


  # Don't remove this route!!!
  get 'profiles/:username' => 'profiles#show'
  resources :profiles, only: [:new]

  resources :payments, only: [:create, :show]

  namespace :admin do
    get '/' => 'dashboard#index'

    resources :organizations
  end

  namespace 'rails_api' do
    resources :people
    resources :clients_organizations
    resources :organizations
    resources :client_profiles
  end

  get 'map' => 'maps#show'

  # Grape API routes will be mounted under the `api` namespace
  mount ::HousingFirst::Api::Base => '/'

  resources :client_profiles
  resources :clients
end

app/models/person.rb
class Person < ApplicationRecord
  enum gender: {
    male:   0,
    female: 1,
    other:  2
  }

  def self.humanized_genders
    genders.keys.map do |gender|
      [gender.humanize, gender]
    end
  end
  

  belongs_to :client
end

app/controllers/rails_api/people_controller.rb
module RailsApi
  class PeopleController < RailsApi::BaseController
    before_action :set_person, only: [:show, :edit, :update, :destroy]

    # GET /people
    # GET /people.json
    def index
      @people = Person.all
    end

    # GET /people/1
    # GET /people/1.json
    def show
    end

    # GET /people/new
    def new
      @person = Person.new
    end

    # GET /people/1/edit
    def edit
    end

    # POST /people
    # POST /people.json
    def create
      @person = Person.new(person_params)

      respond_to do |format|
        if @person.save
          format.json { render :show, status: :created, location: @person }
        else
          format.json { render json: @person.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /people/1
    # PATCH/PUT /people/1.json
    def update
      respond_to do |format|
        if @person.update(person_params)
          format.json { render :show, status: :ok, location: @person }
        else
          format.json { render json: @person.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /people/1
    # DELETE /people/1.json
    def destroy
      @person.destroy
      respond_to do |format|
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_person
        @person = Person.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def person_params
        params.require(:person).permit(:client_id, :first_name, :last_name, :date_of_birth, :gender)
      end
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %>
    <%= f.text_field :client_id %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :date_of_birth %>
    <%= f.date_select :date_of_birth %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.number_field :gender %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Date of birth</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.client_id %></td>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.date_of_birth %></td>
        <td><%= person.gender %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @person.client_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @person.date_of_birth %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @person.gender %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>