config/routes.rb
require 'housing_first/api/base'

Rails.application.routes.draw do

  get '/helps/matching_service_providers' => 'helps#matching_service_providers'
  resources :helps
  resources :intake_forms
  devise_for :users
  get 'pages/index'
  root 'pages#index'

  get '/give' => 'pages#give'
  get '/search' => 'pages#find_client_profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :organizations, only: [:index, :show]


  # Don't remove this route!!!
  get 'profiles/:username' => 'profiles#show'
  resources :profiles, only: [:new]

  resources :payments, only: [:create, :show]

  namespace :admin do
    get '/' => 'dashboard#index'

    resources :organizations
  end

  namespace 'rails_api' do
    resources :people
    resources :clients_organizations
    resources :organizations
    resources :client_profiles
  end

  get 'map' => 'maps#show'

  # Grape API routes will be mounted under the `api` namespace
  mount ::HousingFirst::Api::Base => '/'

  resources :client_profiles
  resources :clients
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < BaseController
    before_action :redirect_if_no_org
    def redirect_if_no_org
      return redirect_to new_admin_organization_path if current_user.needs_organization?
    end

    def index
      @organization = current_user.organization
    end


  end
end

app/controllers/organization/dashboard_controller.rb
module Organization
  class DashboardController < BaseController
    def index
    end
  end
end

app/views/admin/dashboard/index.html.erb
<% if @organization %>
  <div>
    <%= @organization.name %>
  </div>

  <div>
    serving <%= @organization.clients.count %> people in need
  </div>

  <div>
    <% @organization.location.try(:service_offerings).each do |service| %>
      <%= render partial: 'organizations/service', locals: { service: service } %>
    <% end %>
  </div>

  <div>
    <p>Snazzy Dashboard Visualizations Would Go Here</p>
  </div>

<% else %>
  <div>
    Get Started and <%= link_to "set up your organization", admin_new_organizations_path %>
  </div>

<% end %>