config/routes.rb
require 'housing_first/api/base'

Rails.application.routes.draw do

  get '/helps/matching_service_providers' => 'helps#matching_service_providers'
  resources :helps
  resources :intake_forms
  devise_for :users
  get 'pages/index'
  root 'pages#index'

  get '/give' => 'pages#give'
  get '/search' => 'pages#find_client_profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :organizations, only: [:index, :show]


  # Don't remove this route!!!
  get 'profiles/:username' => 'profiles#show'
  resources :profiles, only: [:new]

  resources :payments, only: [:create, :show]

  namespace :admin do
    get '/' => 'dashboard#index'

    resources :organizations
  end

  namespace 'rails_api' do
    resources :people
    resources :clients_organizations
    resources :organizations
    resources :client_profiles
  end

  get 'map' => 'maps#show'

  # Grape API routes will be mounted under the `api` namespace
  mount ::HousingFirst::Api::Base => '/'

  resources :client_profiles
  resources :clients
end

app/models/help.rb
class Help < ApplicationRecord
  enum gender: { male: 0, female: 1, other: 2 }
  enum type: { housing: 0, abuse: 1 }
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  def show
  end

  # GET /helps/new
  def new
    @help_type = params['help_type']
  end

  # GET /helps/1/edit
  def edit
  end

  # POST /helps
  # POST /helps.json
  def create
    matching_service_providers = ::ServiceOffering::FindMatchesForHelpRequest.call!(help_params: help_params)
    service_provider_ids = matching_service_providers.map(&:id)
    return redirect_to '/helps/matching_service_providers',
                       service_providers: service_provider_ids
  end

  def matching_service_providers
    @locations = ::ServiceOffering::FindMatchesForHelpRequest.call!(help_params: help_params)
    @addresses = @locations.map(&:address)
    @hash = Gmaps4rails.build_markers(@addresses) do |address, marker|
      marker.lat address.latitude
      marker.lng address.longitude
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def help_params
      params.permit(:need_housing, :gender, :has_kids, :help_type)
    end
end

app/views/helps/_embedded_map.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDWg_BBVJl6E3OpgIMir2LFiuBNDl5T89w" async defer></script>

<iframe width="300" height="300" frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDWg_BBVJl6E3OpgIMir2LFiuBNDl5T89w&q=<%= coordinates_for address %>"
  allowfullscreen>
</iframe>

app/views/helps/_form.html.erb
<form class="form-horizontal" action="/helps/matching_service_providers" method="get">
  <input type="hidden" name="help_type", value="<%= @help_type %>" />

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Do you need a place to sleep tonight?</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div class="text-center col-md-12 col-sm-12 col-xs-12">
          <div id="need_housing" class="btn-group" data-toggle="buttons">
            <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="need_housing" value="yes"> &nbsp; Yes
            </label>
            <label class="btn btn-info" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="need_housing" value="no"> &nbsp; No
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>What is your gender?</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div class="text-center col-md-12 col-sm-12 col-xs-12">
          <div id="gender" class="btn-group" data-toggle="buttons">
            <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="gender" value="male"> &nbsp; Male
            </label>
            <label class="btn btn-info" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="gender" value="female"> &nbsp; Female
            </label>
            <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="gender" value="other"> &nbsp; Other
            </label>
          </div>
        </div>
        <div class="control-label col-md-1 col-sm-1 col-xs-12"></div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Do you have kids?</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div class="text-center col-md-12 col-sm-12 col-xs-12">
          <div id="has_kids" class="btn-group" data-toggle="buttons">
            <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="has_kids" value="yes"> &nbsp; Yes
            </label>
            <label class="btn btn-info" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="has_kids" value="no"> &nbsp; No
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Are you a victim of domestic abuse?</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div class="text-center col-md-12 col-sm-12 col-xs-12">
          <div id="domestic_abuse" class="btn-group" data-toggle="buttons">
            <label class="btn btn-default <%= 'active' if @help_type == 'abuse' %>" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="domestic_abuse" value="yes" <%= 'selected="true"' if @help_type == 'abuse' %>> &nbsp; Yes
            </label>
            <label class="btn btn-info" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="domestic_abuse" value="no"> &nbsp; No
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>We're Here to Help You</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div class="text-center col-md-12 col-sm-12 col-xs-12">
          <input type="submit" name="find_a_provider" class="btn btn-info" value="Find A Service Provider"></input>
        </div>
      </div>
    </div>
  </div>
</form>

app/views/helps/edit.html.erb
<h1>Editing Help</h1>

<%= render 'form', help: @help %>

<%= link_to 'Show', @help %> |
<%= link_to 'Back', helps_path %>

app/views/helps/index.html.erb
<div class="jumbotron">
  <h1>Get Help</h1>
  <p>Resources to help you live with dignity.</p>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="card card-block with-background">
      <h3 class="card-title">Utilities</h3>
      <p class="card-text">Get help catching up on utility bills.</p>
      <a href="https://www.detroitwaterproject.org/" class="btn btn-primary">Learn More</a>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card card-block with-background">
      <h3 class="card-title">Housing</h3>
      <p class="card-text">Get help finding stable housing.</p>
      <a href="helps/new?help_type=housing" class="btn btn-primary">Find Support</a>
    </div>
  </div>
</div>

app/views/helps/matching_service_providers.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyDBJQbWSgIk_TWZyq9toLHGQ3zY2A56n8E&libraries=places,drawing,geometry"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

<div class="container">
  <div class="col-xs-12">
    <h1 class="margin-left:0">Matching Service Providers Near You</h1>
  </div>
  <% if @locations.empty? %>
      <div class="col-xs-12">
      <h3>We're sorry, but there were no matches found at this time. <small>Please check back later.</small></h3>
      </div>
  <% else %>

  <div class="col-md-5 col-sm-12 col-xs-12">

    <div class="panel panel-default">
      <div class="panel-heading"><h4>Locations</h4></div>
      <div class="panel-body">
        <table class="table">
          <% @locations.each do |location| %>
              <% address = location.address %>
              <tr>
                <td>
                  <address class="pull-right">
                    <% if location.presentable_phone_number %>
                        <abbr title="Phone">P:</abbr> <a href="tel:+<%= location.phoneable %>"><%= location.presentable_phone_number %></a><br>
                    <% end %>
                    <% if location.email %>
                        <a href="mailto:<%= location.email %>"><%= location.email %></a>
                    <% end %>
                  </address>
                  <address>
                    <strong><%= location.organization.name %></strong><br>
                    <%= address.street_1 %><br>
                    <% if address.street_2.present? %>
                        <%= address.street_2 %><br>
                    <% end %>
                    <%= "#{address.city}, #{address.state} #{address.try(:zipcode)}" %>
                  </address>
                </td>
              </tr>
          <% end %>
        </table>
      </div>
    </div>

  </div>
  <div class="col-md-7 col-sm-12 col-xs-12 pull-right">
    <div id="map" style='width: 100%; height: 400px;'></div>
  </div>
  <% end %>

</div>


<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/helps/new.html.erb
<h1>New Help</h1>

<%= render 'form', help: @help %>

<%= link_to 'Back', helps_path %>

app/views/helps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @help.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @help.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @help.gender %>
</p>

<p>
  <strong>Dependents:</strong>
  <%= @help.dependents %>
</p>

<%= link_to 'Edit', edit_help_path(@help) %> |
<%= link_to 'Back', helps_path %>

app/views/helps/step_1.html.erb
<div class="container">
  <div class="col-md-4 col-sm-3 hidden-xs"></div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <h2 class="margin-left:0">Request For Assistance</h2>

    <div class="panel panel-default">
      <div class="panel-heading">Panel heading without title</div>
      <div class="panel-body">
        Panel content
      </div>
    </div>

  </div>
  <div class="col-md-4 col-sm-3 hidden-xs"></div>
</div>